"""HTML report generation."""

from __future__ import annotations

import html
from collections import Counter
from datetime import UTC, datetime

from numasec.models.finding import Finding

_SEVERITY_COLORS = {
    "critical": "#dc3545",
    "high": "#fd7e14",
    "medium": "#ffc107",
    "low": "#17a2b8",
    "info": "#6c757d",
}


def generate_html_report(
    findings: list[Finding],
    target: str = "",
    *,
    include_evidence: bool = True,
) -> str:
    """Generate a self-contained HTML security assessment report."""
    severity_counts = Counter(f.severity.value for f in findings)
    sorted_findings = sorted(
        findings,
        key=lambda f: ["critical", "high", "medium", "low", "info"].index(f.severity.value),
    )
    date_str = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")

    # Build findings HTML
    findings_html: list[str] = []
    for i, f in enumerate(sorted_findings, 1):
        color = _SEVERITY_COLORS.get(f.severity.value, "#6c757d")
        esc = html.escape

        card = f"""
    <div class="finding" style="border-left: 4px solid {color}; padding: 12px; margin: 16px 0; background: #f8f9fa;">
      <h3>{i}. {esc(f.title)}
        <span style="background:{color}; color:#fff; padding:2px 8px; border-radius:4px; font-size:0.8em;">
          {esc(f.severity.value.upper())}
        </span>
      </h3>
      <table style="border-collapse:collapse; margin:8px 0;">"""

        if f.cwe_id:
            card += f"\n        <tr><td><b>CWE:</b></td><td>{esc(f.cwe_id)}</td></tr>"
        if f.cvss_score is not None:
            card += f"\n        <tr><td><b>CVSS:</b></td><td>{f.cvss_score}</td></tr>"
        if f.owasp_category:
            card += f"\n        <tr><td><b>OWASP:</b></td><td>{esc(f.owasp_category)}</td></tr>"
        if f.url:
            card += f"\n        <tr><td><b>URL:</b></td><td><code>{esc(f.url)}</code></td></tr>"
        if f.method:
            card += f"\n        <tr><td><b>Method:</b></td><td>{esc(f.method)}</td></tr>"
        if f.parameter:
            card += f"\n        <tr><td><b>Parameter:</b></td><td><code>{esc(f.parameter)}</code></td></tr>"

        card += "\n      </table>"

        if f.description:
            card += f"\n      <p>{esc(f.description)}</p>"

        if include_evidence and f.evidence:
            card += f"\n      <details><summary>Evidence</summary><pre>{esc(f.evidence[:2000])}</pre></details>"

        if f.remediation_summary:
            card += f"\n      <p><b>Remediation:</b> {esc(f.remediation_summary)}</p>"

        card += "\n    </div>"
        findings_html.append(card)

    # Summary row
    summary_cells = ""
    for sev in ("critical", "high", "medium", "low", "info"):
        count = severity_counts.get(sev, 0)
        color = _SEVERITY_COLORS.get(sev, "#6c757d")
        summary_cells += f'<td style="text-align:center;"><span style="color:{color};font-weight:bold;">{count}</span><br>{sev.capitalize()}</td>'

    # Tools Used section
    tool_summaries: dict[str, int] = {}
    for f in findings:
        if f.tool_used:
            tool_summaries[f.tool_used] = tool_summaries.get(f.tool_used, 0) + 1
    tools_html = ""
    if tool_summaries:
        tools_items = "".join(
            f"<li><b>{html.escape(tool)}</b>: {cnt} finding{'s' if cnt != 1 else ''}</li>"
            for tool, cnt in sorted(tool_summaries.items())
        )
        tools_html = f"\n  <h3>Tools Used</h3>\n  <ul>{tools_items}</ul>"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>numasec Report{" — " + html.escape(target) if target else ""}</title>
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; color: #333; }}
    h1 {{ border-bottom: 2px solid #333; padding-bottom: 8px; }}
    table {{ width: 100%; }}
    td {{ padding: 4px 12px; }}
    pre {{ background: #263238; color: #eee; padding: 12px; border-radius: 4px; overflow-x: auto; white-space: pre-wrap; }}
    code {{ background: #e9ecef; padding: 2px 4px; border-radius: 3px; }}
    details {{ margin: 8px 0; }}
  </style>
</head>
<body>
  <h1>numasec Security Assessment Report</h1>
  <p><b>Target:</b> {html.escape(target) if target else "N/A"} | <b>Date:</b> {date_str} | <b>Findings:</b> {len(findings)}</p>

  <h2>Summary</h2>
  <table style="border:1px solid #ddd; border-collapse:collapse;">
    <tr>{summary_cells}</tr>
  </table>
  {tools_html}

  <h2>Findings</h2>
  {"".join(findings_html) if findings_html else "<p>No security findings were identified.</p>"}

  <footer style="margin-top:32px; padding-top:12px; border-top:1px solid #ddd; color:#999; font-size:0.85em;">
    Generated by numasec
  </footer>
</body>
</html>"""
