"""Attack plan models following PTES methodology.

The AttackPlan is a **living document** — it tracks execution state,
supports dynamic step injection (escalation-driven), and renders
itself as a compact PTT (PentestGPT Pentest Tree) for LLM context.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field

from security_mcp.models.enums import PhaseStatus, PTESPhase

logger = logging.getLogger("security_mcp.models.plan")

# Status markers for the PTT tree rendering
_STATUS_MARKERS: dict[PhaseStatus, str] = {
    PhaseStatus.PENDING: "PENDING",
    PhaseStatus.RUNNING: "IN PROGRESS",
    PhaseStatus.COMPLETED: "DONE",
    PhaseStatus.FAILED: "FAILED",
    PhaseStatus.SKIPPED: "SKIPPED",
}


@dataclass
class AttackStep:
    """Single actionable step within a phase.

    When ``deterministic=True``, the tool is called directly with ``params``
    instead of relying on LLM tool selection.
    """

    id: str
    description: str
    tool: str = ""
    params: dict[str, str] = field(default_factory=dict)
    depends_on: list[str] = field(default_factory=list)
    timeout_seconds: int = 300
    status: PhaseStatus = PhaseStatus.PENDING
    completed: bool = False
    result: str = ""
    deterministic: bool = False


@dataclass
class AttackPhase:
    """A phase of the attack plan (maps to PTES phase)."""

    phase: PTESPhase
    status: PhaseStatus = PhaseStatus.PENDING
    steps: list[AttackStep] = field(default_factory=list)
    parallelizable: bool = False
    timeout_minutes: int = 10

    @property
    def completed(self) -> bool:
        return all(s.completed for s in self.steps)


@dataclass
class AttackPlan:
    """Complete attack plan generated by the deterministic Planner.

    Living document — tracks execution state, supports dynamic step
    injection, and renders itself as a compact PTT tree for LLM context.
    """

    target: str = ""
    scope: str = "quick"  # quick | standard | deep
    phases: list[AttackPhase] = field(default_factory=list)
    created_at: str = ""
    replan_count: int = 0

    @property
    def current_phase(self) -> AttackPhase | None:
        for phase in self.phases:
            if phase.status in (PhaseStatus.PENDING, PhaseStatus.RUNNING):
                return phase
        return None

    @property
    def progress(self) -> float:
        if not self.phases:
            return 0.0
        completed = sum(1 for p in self.phases if p.status == PhaseStatus.COMPLETED)
        return completed / len(self.phases)

    # ------------------------------------------------------------------
    # Living-document methods (W5.1)
    # ------------------------------------------------------------------

    def update_step_status(
        self,
        step_id: str,
        status: PhaseStatus,
        result_summary: str = "",
    ) -> None:
        """Update a step's status by ID, cascading to its containing phase.

        If all steps in a phase are completed/failed/skipped, the phase
        status is automatically updated to COMPLETED.
        """
        for phase in self.phases:
            for step in phase.steps:
                if step.id == step_id:
                    step.status = status
                    step.completed = status in (
                        PhaseStatus.COMPLETED,
                        PhaseStatus.FAILED,
                        PhaseStatus.SKIPPED,
                    )
                    if result_summary:
                        step.result = result_summary

                    # Cascade: if ALL steps in the phase are terminal, mark phase COMPLETED
                    terminal = {PhaseStatus.COMPLETED, PhaseStatus.FAILED, PhaseStatus.SKIPPED}
                    if all(s.status in terminal for s in phase.steps):
                        phase.status = PhaseStatus.COMPLETED
                    elif any(s.status == PhaseStatus.RUNNING for s in phase.steps):
                        phase.status = PhaseStatus.RUNNING

                    logger.debug(
                        "Step %s -> %s (phase %s -> %s)",
                        step_id,
                        status.value,
                        phase.phase.value,
                        phase.status.value,
                    )
                    return

        logger.warning("Step ID '%s' not found in any phase", step_id)

    def add_dynamic_steps(self, phase_name: str, new_steps: list[AttackStep]) -> None:
        """Append new steps to an existing phase (escalation-driven expansion).

        Args:
            phase_name: The PTESPhase value string (e.g. "reconnaissance").
            new_steps: Steps to append.
        """
        for phase in self.phases:
            if phase.phase.value == phase_name:
                phase.steps.extend(new_steps)
                # If phase was already COMPLETED, reopen it
                if phase.status == PhaseStatus.COMPLETED:
                    phase.status = PhaseStatus.RUNNING
                logger.info(
                    "Added %d dynamic steps to phase '%s' (total: %d)",
                    len(new_steps),
                    phase_name,
                    len(phase.steps),
                )
                return

        logger.warning("Phase '%s' not found — cannot add dynamic steps", phase_name)

    def get_pending_steps(self) -> list[AttackStep]:
        """Return all steps with PENDING status across all phases."""
        return [step for phase in self.phases for step in phase.steps if step.status == PhaseStatus.PENDING]

    def to_prompt_context(self) -> str:
        """Render the plan as a compact PTT (PentestGPT Pentest Tree).

        Output format (Unicode box-drawing):
        ```
        Target: http://example.com
        ├── Recon [DONE]
        │   ├── Port scan: 80, 443 open [DONE]
        │   └── Tech: Express, React [DONE]
        ├── Vulnerability Testing [IN PROGRESS]
        │   ├── SQLi on /login [DONE] → FOUND
        │   └── XSS on /search [PENDING]
        └── Exploitation [PENDING]
        ```
        """
        lines = [f"Target: {self.target}"]

        for i, phase in enumerate(self.phases):
            is_last_phase = i == len(self.phases) - 1
            connector = "\u2514\u2500\u2500" if is_last_phase else "\u251c\u2500\u2500"
            phase_marker = _STATUS_MARKERS.get(phase.status, phase.status.value.upper())
            phase_label = phase.phase.value.replace("_", " ").title()
            lines.append(f"{connector} {phase_label} [{phase_marker}]")

            for j, step in enumerate(phase.steps):
                is_last_step = j == len(phase.steps) - 1
                prefix = "    " if is_last_phase else "\u2502   "
                step_connector = "\u2514\u2500\u2500" if is_last_step else "\u251c\u2500\u2500"
                step_marker = _STATUS_MARKERS.get(step.status, step.status.value.upper())

                result_note = ""
                if step.result and step.status == PhaseStatus.COMPLETED:
                    # Truncate result to keep the tree compact
                    truncated = step.result[:60].replace("\n", " ")
                    result_note = f" \u2192 {truncated}"

                lines.append(f"{prefix}{step_connector} {step.description} [{step_marker}]{result_note}")

        return "\n".join(lines)
