name: beta

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  sync:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Setup Git Committer
        id: setup-git-committer
        uses: ./.github/actions/setup-git-committer
        with:
          numasec-app-id: ${{ vars.NUMASEC_APP_ID }}
          numasec-app-secret: ${{ secrets.NUMASEC_APP_SECRET }}

      - name: Install numasec
        run: bun i -g numasec

      - name: Sync beta branch
        env:
          GH_TOKEN: ${{ steps.setup-git-committer.outputs.token }}
          NUMASEC_API_KEY: ${{ secrets.NUMASEC_API_KEY }}
        run: bun script/beta.ts
