name: numasec

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  numasec:
    if: |
      contains(github.event.comment.body, ' /oc') ||
      startsWith(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, ' /numasec') ||
      startsWith(github.event.comment.body, '/numasec')
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Run numasec
        uses: numasec/numasec/github@latest
        env:
          NUMASEC_API_KEY: ${{ secrets.NUMASEC_API_KEY }}
          NUMASEC_PERMISSION: '{"bash": "deny"}'
        with:
          model: numasec/claude-opus-4-5
